Fil.Rouge.Web/Controllers/AgentsController.cs
namespace Fil.Rouge.Web.Controllers
{
    using System.Net;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using Fil.Rouge.Web.Services;
    using Fil.Rouge.Web.Models;

    public class AgentsController : Controller
    {
        //private FilRougeContext db = new FilRougeContext();
        private readonly AgentService agentService = new AgentService();

        // GET: Agents
        public async Task<ActionResult> Index()
        {
            var list = await agentService.GetAll();
            return View(list);
        }

        // GET: Agents/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var agent = await agentService.Get((int)id);
            if (agent == null)
            {
                return HttpNotFound();
            }
            return View(agent);
        }

        // GET: Agents/Create
        public ActionResult Create()
        {
            var vm = new CreateUpdateViewModel();
            return View(vm);
        }

        // POST: Agents/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateUpdateViewModel vm)
        {
            if (ModelState.IsValid)
            {
                await agentService.Create(vm.Agent);
                return RedirectToAction("Index");
            }

            return View(vm);
        }

        // GET: Agents/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var agent = agentService.Get((int)id);
            if (agent == null)
            {
                return HttpNotFound();
            }
            var vm = new CreateUpdateViewModel
            {
                Agent = await agent
            };
            return View(vm);
        }

        // POST: Agents/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(CreateUpdateViewModel vm)
        {
            if (ModelState.IsValid)
            {
                await agentService.Update(vm.Agent.Id, vm.Agent);
                return RedirectToAction("Index");
            }
            return View(vm);
        }

        // GET: Agents/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var agent = await agentService.Get((int)id);
            if (agent == null)
            {
                return HttpNotFound();
            }
            return View(agent);
        }

        // POST: Agents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await agentService.Delete(id).ConfigureAwait(false);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

Fil.Rouge.Web/Controllers/QuizsController.cs
namespace Fil.Rouge.Web.Controllers
{
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using Fil.Rouge.Web.Services;
    using Fil.Rouge.Web.Models;


    public class QuizsController : Controller
    {
        //private FilRougeContext db = new FilRougeContext(); >> On utilise le DAL
        private readonly QuizService quizService = new QuizService();

        // GET: Quizs
        public async Task<ActionResult> Index()
        {
            var list = await quizService.GetAll();
            return View(list);
        }

        // GET: Quizs/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var quiz = await quizService.Get((int)id);
            
            if (quiz == null)
            {
                return HttpNotFound();
            }
            return View(quiz);
        }

        // GET: Quizs/Create
        public async Task<ActionResult> Create()
        {
            var vm = new CreateUpdateViewModel();
            return View(vm);
        }

        // POST: Quizs/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateUpdateViewModel vm)
        {
            if (ModelState.IsValid)
            {
                await quizService.Create(vm.QuizQuestion);
                return RedirectToAction("Index");
            }

            return View(vm);
        }
        
        // GET: Quizs/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var quiz = quizService.Get((int)id);
            if (quiz == null)
            {
                return HttpNotFound();
            }

            var vm = new CreateUpdateViewModel
            {
                QuizQuestion = await quiz
            };
            return View(vm);
        }

        // POST: Quizs/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(CreateUpdateViewModel vm)
        {
            if (ModelState.IsValid)
            {
                await quizService.Update(vm.QuizQuestion.Id, vm.QuizQuestion);
                return RedirectToAction("Index");
            }
            return View(vm);
        }
        /****
        // GET: Quizs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quiz quiz = db.Quizs.Find(id);
            if (quiz == null)
            {
                return HttpNotFound();
            }
            return View(quiz);
        }

        // POST: Quizs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Quiz quiz = db.Quizs.Find(id);
            db.Quizs.Remove(quiz);
            db.SaveChanges();
            return RedirectToAction("Index");
        }*/

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
        
    }
}

Fil.Rouge.Web/Views/Shared/_Footer.cshtml
<div id="templatemo_footer_wrapper">

    <div id="templatemo_footer">

        <div class="section_w180">
            <div class="header_05">Services</div>
            <div class="section_w180_content">
                <ul class="footer_menu_list">
                    <li><a href="#">Lorem ipsum dolor</a></li>
                    <li><a href="#">Cum sociis</a></li>
                    <li><a href="#">Donec quam</a></li>
                    <li><a href="#">Nulla consequat</a></li>
                    <li><a href="#">In enim justo</a></li>
                </ul>
            </div>
        </div>

        <div class="section_w180">
            <div class="header_05">About</div>
            <div class="section_w180_content">
                <ul class="footer_menu_list">
                    <li><a href="#">Nullam quis</a></li>
                    <li><a href="#">Sed consequat</a></li>
                    <li><a href="#">Cras dapibus</a></li>
                    <li><a href="#">Lorem ipsum dolor</a></li>
                    <li><a href="#">Cum sociis</a></li>
                </ul>
            </div>
        </div>

        <div class="section_w180">
            <div class="header_05">Cool links</div>
            <div class="section_w180_content">
                <ul class="footer_menu_list">
                    <li><a href="#">Aenean vulputate</a></li>
                    <li><a href="#">Etiam ultricies</a></li>
                    <li><a href="#">Nullam quis</a></li>
                    <li><a href="#">Sed consequat</a></li>
                    <li><a href="#">Cras dapibus</a></li>
                </ul>
            </div>
        </div>

        <div class="section_w180">
            <div class="header_05">Contact</div>

            <div class="section_w180_content">

                <ul class="footer_menu_list">
                    <li><a href="#">Donec quam</a></li>
                    <li><a href="#">Nulla consequat</a></li>
                    <li><a href="#">In enim justo</a></li>
                    <li><a href="#">Aenean vulputate</a></li>
                    <li><a href="#">Etiam ultricies</a></li>
                </ul>
            </div>
        </div>
        <div class="margin_bottom_20"></div>
        Copyright © 2021 <a href="#">Cabinet recrutement</a>
        <div class="cleaner"></div>
    </div>
</div>

Fil.Rouge.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>


<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/style.css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("metatags", false)
</head>
<body>
    @Html.Partial("_TopMenu")
    <div class="container">
        @RenderBody()
    </div>
    @Html.Partial("_Footer")
</body>
</html>

Fil.Rouge.Web/Views/Shared/_TopMenu.cshtml
<div id="templatemo_header_wrapper">
    <div id="templatemo_header">

        <div id="site_logo"></div>

        <div id="templatemo_menu">
            <div id="templatemo_menu_left"></div>
            <ul>
                <li><a href="~/Home/Index">Home</a></li>
                <li>@Html.ActionLink("Quiz Manager", "Index", "Quizs")</li>
                <li>@Html.ActionLink("Agent Manager", "Index", "Agents")</li>
            </ul>
        </div>
    </div>
</div>